/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class GamePlay extends javax.swing.JFrame {
    
    //Khai báo biến
    int win = 0;
    int lose = 0;
    int draw = 0;

    /**
     * Creates new form GameView
     */
    public GamePlay() {
        //Hiện hộp thoại thông báo trước khi bắt đầu game
        JOptionPane.showMessageDialog(null, "You need to win 5 times to complete the game", "Note", JOptionPane.DEFAULT_OPTION);
     
        getContentPane().setBackground(new Color(214, 251, 248));//Set màu cho background
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        rock = new javax.swing.JButton();
        paper = new javax.swing.JButton();
        scissors = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        wins = new javax.swing.JLabel();
        loses = new javax.swing.JLabel();
        draws = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ROCK - PAPER - SCISSORS GAME");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(730, 700));
        setResizable(false);

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rps (4).png"))); // NOI18N
        img2.setVisible(false);

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rps (2).png"))); // NOI18N
        img1.setVisible(false);

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rps (3).png"))); // NOI18N
        img3.setVisible(false);

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rps (2).png"))); // NOI18N
        img4.setVisible(false);

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rps (4).png"))); // NOI18N
        img5.setVisible(false);

        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rps (3).png"))); // NOI18N
        img6.setVisible(false);

        rock.setBackground(new java.awt.Color(255, 175, 64));
        rock.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        rock.setText("ROCK");
        rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockActionPerformed(evt);
            }
        });

        paper.setBackground(new java.awt.Color(255, 89, 103));
        paper.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        paper.setText("PAPER");
        paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperActionPerformed(evt);
            }
        });

        scissors.setBackground(new java.awt.Color(104, 191, 96));
        scissors.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        scissors.setText("SCISSORS");
        scissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Computer");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Player");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("Choose your option");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("WIN");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("LOSE");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("DRAW");

        wins.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        wins.setText("0");

        loses.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        loses.setText("0");

        draws.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        draws.setText("0");

        txt.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(img1)
                                    .addComponent(img2))))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(img4)
                                    .addComponent(img5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wins)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(loses)))
                        .addGap(191, 191, 191)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(draws))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel4)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img1)
                    .addComponent(img2)
                    .addComponent(img4)
                    .addComponent(img5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img3)
                            .addComponent(img6))))
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wins)
                                .addGap(18, 18, 18)
                                .addComponent(loses)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(draws))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Nút PAPER
    private void paperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperActionPerformed
        // TODO add your handling code here:
        
        //Set ảnh ẩn và hiện
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(false);
        img5.setVisible(true);
        img6.setVisible(false);
        
        //Tạo biến random
        Random cpt = new Random();
        int b = cpt.nextInt(3) + 1;//Random từ 1-3
        jLabel1.setText(Integer.toString(b));//Set số vào label(convert from int to string)
        jLabel1.setVisible(false);//Ẩn label đã set số đi(để nhìn cho đẹp)

        //Mình chọn PAPER và máy tính random
        switch (b) {
            case 1://Random ra ROCK
                img1.setVisible(true);//Hiện ảnh rock ra
                txt.setText("WIN!");//Set WIN! cho label txt
                win += 1;//Đếm số lần thắng
                wins.setText(Integer.toString(win));//Thêm số lần thắng đã đếm vào label wins(convert from int to string)
                break;
            case 2://Random ra PAPER
                img2.setVisible(true);//Hiện ảnh paper ra
                txt.setText("DRAW!");//Set DRAW! cho label txt
                draw += 1;//Đếm số lần hòa
                draws.setText(Integer.toString(draw));//Thêm số lần hòa đã đếm vào label draws(convert from int to string)
                break;
            case 3://Random ra SCISSORS
                img3.setVisible(true);//Hiện ảnh scissors ra
                txt.setText("LOSE!");//Set LOSE! cho label txt
                lose += 1;//Đếm số lần thua
                loses.setText(Integer.toString(lose));//Thêm số lần thua đã đếm vào label loses(convert from int to string)
                break;
        }
        if (win == 5) {
            //Hiện hộp thoại(yes_no)
            int choose = JOptionPane.showConfirmDialog(null, "YOU WIN! Do you want to play again?", "Select option...", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {//Chọn yes sẽ ẩn GamePlay và hiện StartGame
                setVisible(false);
                new StartGame().setVisible(true);
            }
            if (choose == JOptionPane.NO_OPTION) {//Chọn no sẽ đóng chương trình
                System.exit(0);
            }
        }
        if (lose == 5) {
            int choose = JOptionPane.showConfirmDialog(null, "YOU LOST! Do you want to play again?", "Select option...", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {
                setVisible(false);
                new StartGame().setVisible(true);
            }
            if (choose == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_paperActionPerformed

    private void rockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockActionPerformed
        // TODO add your handling code here:
        
        //Set ảnh ẩn và hiện
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(true);
        img5.setVisible(false);
        img6.setVisible(false);
        
        //Tạo biến random
        Random cpt = new Random();
        int b = cpt.nextInt(3) + 1;
        jLabel1.setText(Integer.toString(b));
        jLabel1.setVisible(false);
        
        //Mình chọn ROCK và máy tính random
        switch (b) {
            case 1://Random ra ROCK
                img1.setVisible(true);
                txt.setText("DRAW!");
                draw += 1;
                draws.setText(Integer.toString(draw));
                break;
            case 2://Random ra PAPER
                img2.setVisible(true);
                txt.setText("LOSE!");
                lose += 1;
                loses.setText(Integer.toString(lose));
                break;
            case 3://Random ra SCISSORS
                img3.setVisible(true);
                txt.setText("WIN!");
                win += 1;
                wins.setText(Integer.toString(win));
                break;
        }
        if (win == 5) {
            int choose = JOptionPane.showConfirmDialog(null, "YOU WIN! Do you want to play again?", "Select option...", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {
                setVisible(false);
                new StartGame().setVisible(true);
            }
            if (choose == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
        if (lose == 5) {
            int choose = JOptionPane.showConfirmDialog(null, "YOU LOST! Do you want to play again?", "Select option...", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {
                setVisible(false);
                new StartGame().setVisible(true);
            }
            if (choose == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_rockActionPerformed

    private void scissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsActionPerformed
        // TODO add your handling code here:
        
        //Set ảnh ẩn và hiện
        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(false);
        img5.setVisible(false);
        img6.setVisible(true);
        
        //Tạo biến random
        Random cpt = new Random();
        int b = cpt.nextInt(3) + 1;
        jLabel1.setText(Integer.toString(b));
        jLabel1.setVisible(false);
        
        //Mình chọn SCISSORS và máy tính random
        switch (b) {
            case 1://Random ra ROCK
                img1.setVisible(true);
                txt.setText("LOSE!");
                lose += 1;
                loses.setText(Integer.toString(lose));
                break;
            case 2://Random ra PAPER
                img2.setVisible(true);
                txt.setText("WIN!");
                win += 1;
                wins.setText(Integer.toString(win));
                break;
            case 3://Random ra SCISSORS
                img3.setVisible(true);
                txt.setText("DRAW!");
                draw += 1;
                draws.setText(Integer.toString(draw));
                break;
        }
        if (win == 5) {
            int choose = JOptionPane.showConfirmDialog(null, "YOU WIN! Do you want to play again?", "Select option...", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {
                setVisible(false);
                new StartGame().setVisible(true);
            }
            if (choose == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
        if (lose == 5) {
            int choose = JOptionPane.showConfirmDialog(null, "YOU LOST! Do you want to play again?", "Select option...", JOptionPane.YES_NO_OPTION);
            if (choose == JOptionPane.YES_OPTION) {
                setVisible(false);
                new StartGame().setVisible(true);
            }
            if (choose == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_scissorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel draws;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel loses;
    private javax.swing.JButton paper;
    private javax.swing.JButton rock;
    private javax.swing.JButton scissors;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel wins;
    // End of variables declaration//GEN-END:variables
}
